name: Create Release

on:
  push:
    branches:
      - main
    paths:
      - "Cargo.toml"

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract version from Cargo.toml
        id: extract_version
        run: |
          version=$(grep '^version' Cargo.toml | sed -E 's/version = "(.*)"/\1/')
          echo "::set-output name=version::$version"

      - name: Check if tag exists
        id: check_tag
        run: |
          version=v${{ steps.extract_version.outputs.version }}
          if git rev-parse "$version" >/dev/null 2>&1; then
            echo "Tag $version already exists."
            exit 0
          else
            echo "Tag $version does not exist."
            echo "::set-output name=tag::$version"
          fi

      - name: Create Release
        if: steps.check_tag.outputs.tag
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.check_tag.outputs.tag }}
          release_name: ${{ steps.extract_version.outputs.version }}
          body: |
            Changes in this release:
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
