name: Publish Crate

on:
  release:
    types: [published]

  workflow_run:
    workflows:
      - "Create Release"
    types:
      - completed
    conclusions:
      - success

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Publish crate
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
