name: Publish Crate

on:
  release:
    types: [published]
  workflow_run:
    workflows:
      - "Create Release"
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: ryohidaka/action-cargo-publish@v0.1.0
        with:
          path: "."
          token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          dry-run: false
